spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
              - Authorization
            exposed-headers: ["*"]
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
